In [1]:
import pandas as pd

In [2]:
a = pd.read_csv("SOCR-HeightWeight.csv")

In [3]:
a.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

In [4]:
a.isnull().sum()

Index             0
Height(Inches)    0
Weight(Pounds)    0
dtype: int64

In [5]:
a.isnull().any()

Index             False
Height(Inches)    False
Weight(Pounds)    False
dtype: bool

In [6]:
x=a[["Height(Inches)"]]
x

       Height(Inches)
0            65.78331
1            71.51521
2            69.39874
3            68.21660
4            67.78781
...               ...
24995        69.50215
24996        64.54826
24997        64.69855
24998        67.52918
24999        68.87761

[25000 rows x 1 columns]

In [7]:
y=a[["Weight(Pounds)"]]
y

       Weight(Pounds)
0            112.9925
1            136.4873
2            153.0269
3            142.3354
4            144.2971
...               ...
24995        118.0312
24996        120.1932
24997        118.2655
24998        132.2682
24999        124.8742

[25000 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [10]:
print("X train")
x_train

X train

       Height(Inches)
12756        70.03377
5652         68.34809
11186        70.20339
3170         66.79884
8078         66.83183
...               ...
16905        67.10295
5968         68.28835
6650         70.09777
5781         67.97316
17514        66.23063

[20000 rows x 1 columns]

In [11]:
print("Y train")
y_train

Y train

       Weight(Pounds)
12756        120.3446
5652         122.9334
11186        137.6673
3170         132.1508
8078         135.5006
...               ...
16905        136.7551
5968         129.5032
6650         148.3039
5781         131.4318
17514        125.2783

[20000 rows x 1 columns]

In [12]:
print("X test")
x_test

X test

       Height(Inches)
24125        67.49912
19876        69.87889
15173        65.70932
13545        70.42984
22755        66.66785
...               ...
4358         67.79903
8472         73.95409
13688        66.51669
3028         66.65320
4560         67.93284

[5000 rows x 1 columns]

In [13]:
print("Y test")
y_test

Y test

       Weight(Pounds)
24125        134.2321
19876        139.1403
15173        124.1531
13545        136.3197
22755        137.9687
...               ...
4358         131.8900
8472         145.2695
13688        123.0958
3028         111.2623
4560         111.6216

[5000 rows x 1 columns]

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
model=LinearRegression()

In [16]:
model.fit(x_train,y_train)

LinearRegression()

In [17]:
y_pred=model.predict(x_test)

In [18]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [19]:
mean_absolute_error(y_test,y_pred)

8.074967067127513

In [20]:
mean_squared_error(y_test,y_pred)

101.92149336141549

In [21]:
r2_score(y_test,y_pred)

0.2446383497690271

In [22]:
import joblib

In [23]:
joblib.dump(model, "linear.pkl")

['linear.pkl']

In [24]:
import joblib

In [25]:
a=joblib.load("linear.pkl")

In [26]:
a.predict([[100]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[226.14697262]])

#Practice question

In [27]:
import pandas as pd
df=pd.read_csv('data.csv')

In [28]:
df.head(5)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [29]:
x=df[['bedrooms','bathrooms','sqft_living','sqft_lot','floors','waterfront','view','condition','sqft_above','sqft_basement','yr_built','yr_renovated']]
y=df[['price']]

In [30]:
df.isnull().any()

date             False
price            False
bedrooms         False
bathrooms        False
sqft_living      False
sqft_lot         False
floors           False
waterfront       False
view             False
condition        False
sqft_above       False
sqft_basement    False
yr_built         False
yr_renovated     False
street           False
city             False
statezip         False
country          False
dtype: bool

In [31]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [34]:
x_train

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
3939,4.0,5.00,4110,43560,2.0,0,0,4,4110,0,1978,2000
3282,3.0,1.00,1270,7566,1.0,0,0,4,1270,0,1958,1972
2058,3.0,2.50,1480,1961,2.0,0,0,3,1480,0,2005,0
2019,4.0,2.50,2040,6034,2.0,0,0,3,2040,0,1990,2009
3451,4.0,2.25,2070,7350,2.0,0,0,4,2070,0,1977,0
...,...,...,...,...,...,...,...,...,...,...,...,...
4291,3.0,1.00,1470,6500,1.0,0,0,4,1470,0,1953,1983
4094,2.0,1.00,880,4000,1.0,0,0,3,880,0,1940,1996
1698,2.0,1.00,1170,6000,1.0,0,0,4,970,200,1941,1998
1412,3.0,2.50,2610,7256,2.0,0,0,3,2610,0,2014,0
1038,4.0,2.50,2670,8765,2.0,0,0,3,2670,0,2006,0

In [35]:
from sklearn.linear_model import LinearRegression

In [36]:
model=LinearRegression()

In [37]:
model.fit(x_train,y_train)

LinearRegression()

In [38]:
y_pred=model.predict(x_test)

In [39]:
model.predict(x_test)

array([[ 401708.6498517 ],
       [ 634035.26153932],
       [ 420100.06405791],
       [ 238179.37553895],
       [ 558524.12763414],
       [ 558757.35136791],
       [ 637621.31695175],
       [ 440162.59417038],
       [ 445424.22241184],
       [ 633409.33447   ],
       [ 415686.06470111],
       [1165860.61963269],
       [ 491613.68473231],
       [ 610674.52873126],
       [ 403155.70998534],
       [ 276346.29039992],
       [ 385156.09698411],
       [ 527203.44305555],
       [ 394216.35201991],
       [ 372676.45333724],
       [ 470417.6806872 ],
       [ 580164.34046877],
       [ 474001.91330351],
       [ 611173.46323926],
       [ 269757.47291779],
       [ 324792.46504459],
       [ 301568.597496  ],
       [ 710564.32488295],
       [ 421777.23590166],
       [ 532403.16417227],
       [ 421993.43454088],
       [ 303128.83548166],
       [ 533118.03976092],
       [ 504948.07913066],
       [ 474539.10058648],
       [ 912953.85821201],
       [ 437479.17373249],
       [ 261984.04124339],
       [ 942807.03915893],
       [ 472846.21510185],
       [ 764804.33172868],
       [ 505796.66314933],
       [ 717823.65494964],
       [ 620120.39053637],
       [ 396427.50898449],
       [ 994474.42508759],
       [ 287461.44422331],
       [ 279992.00447342],
       [ 602829.90730342],
       [ 290755.54742477],
       [ 603170.98453977],
       [ 569460.94281121],
       [ 648563.68912029],
       [1190828.24845656],
       [ 564332.46919215],
       [ 447230.79632955],
       [ 377263.93955323],
       [ 563576.819637  ],
       [ 898992.3593598 ],
       [ 521874.61783589],
       [ 639326.92697918],
       [ 647268.87016392],
       [ 328960.74925979],
       [ 382675.69185627],
       [ 520222.91492801],
       [ 506658.68309547],
       [ 636358.25935947],
       [ 313620.10688286],
       [ 346180.32501457],
       [ 342433.5679799 ],
       [ 407614.07749335],
       [ 362394.24432689],
       [1230130.56727593],
       [ 460154.90847919],
       [ 476684.37649328],
       [ 888465.97785278],
       [ 648719.42924478],
       [ 354962.08191076],
       [ 910758.8180532 ],
       [ 687029.78053744],
       [ 781305.94608802],
       [ 394911.928489  ],
       [ 289173.29593244],
       [ 603520.42271582],
       [ 735361.82730584],
       [ 648593.10467436],
       [ 655959.63600734],
       [ 641761.10813088],
       [ 348447.76414145],
       [ 605546.81127361],
       [ 236258.21850061],
       [ 430967.05788929],
       [ 336773.58497064],
       [ 398018.3602155 ],
       [ 357027.97875575],
       [ 732029.36494776],
       [ 176635.67067777],
       [ 468125.5016218 ],
       [ 856931.45208645],
       [ 481376.50725859],
       [ 127382.49722183],
       [ 606432.77923599],
       [1233448.88497131],
       [ 372489.53651585],
       [ 453550.83497288],
       [ 557041.09195811],
       [ 617228.10675689],
       [1443942.81766991],
       [ 383719.65970824],
       [ 556348.93559359],
       [ 592715.35408367],
       [ 809479.166286  ],
       [ 402288.89481212],
       [ 438365.60874025],
       [ 188421.86676707],
       [ 252971.84411725],
       [1151152.37153428],
       [ 440769.64173293],
       [ 607231.01389274],
       [ 621526.00823922],
       [ 461807.70810232],
       [ 358678.59050313],
       [ 274548.44565514],
       [ 789753.11767355],
       [1253362.3629222 ],
       [ 233202.93068407],
       [ 525270.76534451],
       [ 267627.64158109],
       [ 344208.51929696],
       [ 516462.01471026],
       [ 448120.50036658],
       [ 394577.43780822],
       [ 362158.59908944],
       [ 406814.28412781],
       [ 407412.56685002],
       [ 552847.22052469],
       [ 335969.67457839],
       [ 384932.6461757 ],
       [ 216202.46353248],
       [ 372078.1449521 ],
       [ 386820.11615229],
       [ 656091.76728279],
       [ 595688.18125656],
       [ 747467.36781114],
       [ 236099.32872655],
       [ 226430.56697872],
       [ 332864.68095552],
       [ 573643.51393665],
       [ 857972.38078596],
       [ 354037.43356186],
       [ 337600.08662796],
       [ 212915.99615552],
       [ 307526.20482798],
       [ 542576.79228695],
       [ 595386.58046146],
       [ 580879.44180324],
       [ 340325.9153697 ],
       [ 346075.9088617 ],
       [ 758886.18487294],
       [ 811914.94717263],
       [ 404874.07700339],
       [1342549.82637719],
       [ 414563.74895907],
       [ 859741.20483682],
       [ 562281.5907915 ],
       [ 366743.7270029 ],
       [ 480325.19368024],
       [ 435384.04580334],
       [ 334884.61136814],
       [ 314585.97298586],
       [ 393743.85249572],
       [ 862551.24030777],
       [ 766377.39895604],
       [ 318460.91310386],
       [ 539700.7612189 ],
       [ 540306.54186358],
       [1077394.43842614],
       [ 331457.6566473 ],
       [1450076.15793257],
       [ 208144.14766246],
       [ 415201.38899685],
       [ 359035.29014433],
       [ 562560.18042393],
       [ 265022.73215495],
       [ 405869.55252123],
       [ 437533.41209602],
       [1205372.66983205],
       [1114871.41436205],
       [ 684875.35008648],
       [ 293759.76865047],
       [ 339248.49012817],
       [ 646235.70859112],
       [ 403679.61020861],
       [ 477099.7100788 ],
       [ 220545.29924687],
       [ 692349.15374718],
       [ 286472.57059204],
       [ 354069.39293707],
       [ 573894.74702987],
       [ 555723.89947651],
       [ 420303.46410077],
       [ 779188.34523416],
       [ 902800.6095634 ],
       [ 364348.0247896 ],
       [ 715499.69784812],
       [ 416415.92045459],
       [ 520407.99003551],
       [ 325438.93226981],
       [ 486608.67236994],
       [ 295624.00483162],
       [ 647033.21853915],
       [ 318647.20782451],
       [ 537198.57544401],
       [ 563629.70095581],
       [1477129.56485629],
       [ 674801.68441005],
       [1071096.56088913],
       [ 499275.8326648 ],
       [1051094.83164773],
       [ 491171.09615745],
       [ 234986.54930925],
       [ 839150.40302264],
       [ 957444.10336285],
       [ 473069.43614391],
       [ 738517.17617088],
       [ 423506.92775092],
       [ 767596.18730661],
       [ 791438.44113776],
       [ 554480.78837884],
       [ 298971.93582262],
       [ 662915.76004714],
       [ 395718.06766485],
       [ 316777.77064812],
       [ 244622.17633049],
       [ 532696.66067983],
       [ 590687.62744579],
       [ 577661.78520055],
       [ 627673.37959426],
       [ 844138.67878196],
       [ 398850.90300274],
       [ 702971.68148702],
       [ 572407.61244351],
       [ 355669.87747758],
       [ 496062.25224595],
       [ 271410.39834249],
       [ 299596.67534486],
       [ 707730.13176238],
       [ 180441.92301003],
       [ 616074.66856787],
       [ 504360.55841104],
       [ 252420.35909604],
       [ 483301.23985999],
       [ 295810.13294483],
       [ 632360.50032045],
       [ 499319.0714777 ],
       [ 650988.10439517],
       [ 555556.48155771],
       [ 286826.36851187],
       [ 447302.11561802],
       [ 760287.98248977],
       [ 454026.3180305 ],
       [ 267142.80393456],
       [ 407591.38886942],
       [ 461439.80844385],
       [ 401631.36444946],
       [ 974201.93289862],
       [ 358345.6119626 ],
       [1210368.54800507],
       [ 254594.16914438],
       [ 436812.40854954],
       [1494792.996465  ],
       [ 381380.08557079],
       [ 226069.36386169],
       [ 562419.47658217],
       [ 804083.76425802],
       [ 346353.18356293],
       [ 478542.14687327],
       [ 731559.65556875],
       [ 744185.38395292],
       [1137878.14991905],
       [ 301076.65563954],
       [ 593233.21066808],
       [ 403815.47146515],
       [ 888200.05641129],
       [ 422087.87135695],
       [ 459349.06395049],
       [ 513932.20207724],
       [ 605529.99196573],
       [ 506099.70596281],
       [ 974644.47811911],
       [1117281.21396867],
       [ 317341.82229791],
       [ 801787.66465205],
       [ 404663.41460769],
       [ 483657.92104115],
       [ 838639.58317822],
       [ 445141.45179779],
       [ 763507.43113173],
       [ 340532.46264759],
       [ 395203.85200634],
       [ 354269.80165706],
       [ 377816.24346849],
       [ 581836.73905588],
       [ 865290.54916492],
       [ 545464.61601337],
       [ 499905.03084056],
       [ 623366.12537471],
       [ 234164.32681828],
       [ 743922.56601883],
       [ 694065.89356909],
       [ 545623.41583508],
       [ 202158.22983819],
       [ 584796.57970353],
       [ 728866.66266935],
       [ 383573.76756528],
       [ 777434.41394549],
       [ 453803.55009799],
       [1238684.70095376],
       [ 638709.55092901],
       [ 417645.46678608],
       [ 460566.87357507],
       [ 512793.49905908],
       [ 538857.64852048],
       [ 429344.01645084],
       [ 461966.41797297],
       [ 735170.15965587],
       [ 392741.04768988],
       [ 393817.62994256],
       [ 283696.21322942],
       [ 512068.66120911],
       [ 304917.92073532],
       [ 374310.64608496],
       [ 405683.13515357],
       [ 373673.44749634],
       [ 709432.99209318],
       [ 569862.87047784],
       [ 300531.72666271],
       [ 410023.63265958],
       [1702231.30403936],
       [ 484362.48409966],
       [ 435921.2491537 ],
       [ 621805.18317873],
       [ 423306.36791204],
       [ 393191.64114418],
       [ 570157.18645583],
       [ 182247.76394905],
       [ 592965.40945103],
       [ 484917.0316064 ],
       [ 210747.54459575],
       [ 404771.60258881],
       [ 442277.30362953],
       [ 363583.62688731],
       [ 397575.53495147],
       [ 473849.76111685],
       [ 438692.9786949 ],
       [ 168019.03819356],
       [ 337971.74441899],
       [ 273300.19507355],
       [ 385807.57620735],
       [ 227553.01158719],
       [ 242793.77554476],
       [1116059.86039359],
       [ 697368.19529165],
       [ 477873.87246791],
       [ 319306.26328534],
       [ 513421.91954519],
       [ 288891.32619336],
       [ 307537.73073932],
       [ 247565.57272488],
       [ 229162.93519606],
       [ 542594.8140237 ],
       [ 505497.88230709],
       [ 511268.02549745],
       [ 218997.87949071],
       [ 763649.22031162],
       [1073041.20890633],
       [ 332041.37608634],
       [ 573751.53784071],
       [1307789.99059067],
       [ 810999.84977543],
       [ 443691.29333095],
       [ 598642.09106582],
       [ 433106.41249425],
       [ 778087.74509645],
       [ 720425.67042277],
       [ 645944.70721549],
       [1061420.10617649],
       [ 776140.80833383],
       [ 818207.53679673],
       [ 606947.80507179],
       [ 445268.65050982],
       [ 833589.40840397],
       [ 443419.89039596],
       [ 598456.49623888],
       [ 409813.48828706],
       [ 440411.20200491],
       [ 524643.51080825],
       [ 345930.11772041],
       [ 833501.15993919],
       [ 596255.83676385],
       [ 315335.20079998],
       [ 202624.8255813 ],
       [ 487915.85363115],
       [ 352921.87192175],
       [ 304986.35829108],
       [ 550551.15115246],
       [ 537004.38598075],
       [ 724701.23853297],
       [ 742191.51802776],
       [ 507598.46656456],
       [ 369914.39115119],
       [ 751444.03333684],
       [ 751219.91484454],
       [ 447679.91878125],
       [ 429649.87197048],
       [ 366629.33130794],
       [ 736043.46327116],
       [ 466233.06870333],
       [ 522411.58092999],
       [1018805.93694258],
       [ 372615.61998046],
       [ 321573.2259673 ],
       [ 268800.64563986],
       [ 343960.17033148],
       [ 472663.89208857],
       [ 432527.69809713],
       [ 226311.4193951 ],
       [ 308930.42088427],
       [ 319626.53301851],
       [ 395511.97078001],
       [ 853360.69404147],
       [ 850289.01053276],
       [ 268211.6280484 ],
       [ 407537.79304451],
       [1394279.10138723],
       [ 500936.97064658],
       [1308907.44264963],
       [ 550983.8439507 ],
       [ 569898.00386321],
       [ 474159.25762419],
       [ 635835.20145983],
       [ 358314.00469059],
       [ 982442.58166769],
       [ 555076.7841048 ],
       [ 696827.67810736],
       [ 469563.25999476],
       [ 568496.12304231],
       [ 563288.75986999],
       [ 451211.84556676],
       [ 429911.20215735],
       [ 251092.91787557],
       [ 411549.05907317],
       [ 701940.0657553 ],
       [ 451719.31931953],
       [ 289208.67180032],
       [ 545488.44805376],
       [ 313155.29028925],
       [1007718.90704043],
       [ 441378.90836896],
       [1290754.8914332 ],
       [ 647649.76369142],
       [ 653635.60989311],
       [ 648659.73039389],
       [ 710750.9466141 ],
       [ 545197.17780553],
       [ 641702.44662099],
       [1400022.97009066],
       [ 338447.58272151],
       [ 837249.01125105],
       [ 543562.69567457],
       [ 641855.41659257],
       [ 217998.83172628],
       [ 638836.23116442],
       [ 926721.9887724 ],
       [ 369567.13501072],
       [ 512845.26476383],
       [ 691252.71793323],
       [ 189570.81078064],
       [ 796173.02799586],
       [ 471368.20302115],
       [ 125574.28845187],
       [ 549174.97049309],
       [ 444002.55690766],
       [1021515.18696055],
       [1333441.0132755 ],
       [ 166682.1435013 ],
       [ 474331.20835318],
       [ 316932.98709457],
       [ 409397.39356441],
       [ 276430.21558815],
       [ 321948.22764267],
       [ 705744.73908261],
       [ 729024.4955941 ],
       [ 438787.64130079],
       [ 432482.51505906],
       [ 281647.87305073],
       [1234395.96982399],
       [ 520641.89200279],
       [ 381692.25166048],
       [ 298439.1005931 ],
       [ 845374.70650611],
       [ 524226.23964028],
       [ 169224.51377041],
       [ 553287.49677284],
       [1036509.85344556],
       [ 694868.05819505],
       [ 451996.60095716],
       [ 434378.50546213],
       [ 630320.83823191],
       [ 405668.18027166],
       [ 649136.52735174],
       [ 303020.15909948],
       [ 278146.13947931],
       [ 789881.90981724],
       [ 788055.6605549 ],
       [ 570451.09141365],
       [ 253137.2883676 ],
       [ 381179.07121764],
       [ 746334.83435957],
       [ 313713.09995699],
       [ 831573.20431654],
       [ 877525.92758101],
       [ 572672.40115086],
       [ 285803.76970763],
       [ 652315.30346633],
       [ 313914.54772135],
       [ 629437.20656865],
       [ 450519.39184566],
       [ 642088.79746112],
       [ 943330.59098448],
       [ 972713.59278875],
       [ 440710.60264849],
       [ 240829.83971681],
       [ 726173.17771596],
       [ 260587.52035439],
       [ 486181.25816415],
       [ 196001.21202104],
       [ 632493.36905356],
       [ 442578.32753113],
       [ 924562.01021009],
       [ 238465.35419893],
       [ 948452.53951194],
       [1011221.68261187],
       [ 474030.09542029],
       [ 363607.77033192],
       [ 639637.15856011],
       [ 655234.92749904],
       [ 596850.06598484],
       [1017499.13203707],
       [ 498297.63148623],
       [ 322022.322787  ],
       [ 316514.91861095],
       [ 393526.95869959],
       [ 323482.69492845],
       [ 266385.16851668],
       [ 230591.04097242],
       [ 458631.53953973],
       [ 253336.87742423],
       [ 499978.83918948],
       [ 609031.84405154],
       [ 608212.13264323],
       [ 972780.21288687],
       [ 240846.8440945 ],
       [ 352038.40868852],
       [ 378057.72769531],
       [ 514092.72219568],
       [ 386189.6218839 ],
       [ 903679.33746612],
       [ 411027.12131997],
       [ 955230.5011267 ],
       [ 364045.00345322],
       [ 417578.68896491],
       [ 360838.32803805],
       [ 555335.27967987],
       [ 518639.49440133],
       [ 367048.44099822],
       [ 600430.07497108],
       [ 342833.04220748],
       [ 628831.14461312],
       [ 484194.30121653],
       [ 340218.82156894],
       [ 443596.54864721],
       [ 443153.43813687],
       [ 415871.33160448],
       [ 340595.95329928],
       [ 638605.16841766],
       [ 793618.11939176],
       [ 698352.10938937],
       [ 627413.43776354],
       [ 276136.21458144],
       [ 437256.15338744],
       [ 324723.31885196],
       [ 720637.95647851],
       [ 390384.32231828],
       [ 494171.89692395],
       [ 251437.47515644],
       [ 362953.4072676 ],
       [ 311279.65371697],
       [ 407593.51529023],
       [ 284332.3368012 ],
       [ 535177.16216463],
       [ 469713.72751621],
       [ 576582.21591978],
       [ 406667.92446659],
       [ 589078.08538196],
       [ 651526.72724032],
       [ 540578.74272962],
       [1533967.59869048],
       [1367343.29952103],
       [ 266064.07643   ],
       [ 461806.81011761],
       [ 423559.50238089],
       [ 784851.97024147],
       [ 445502.47247374],
       [1114845.33792596],
       [ 693811.3047852 ],
       [ 597339.94838542],
       [ 486180.36078543],
       [ 404489.53744166],
       [ 424183.77840715],
       [ 780637.11333208],
       [ 413383.42421756],
       [ 447748.15387053],
       [ 528187.08198502],
       [ 253349.14895706],
       [ 424831.9401628 ],
       [ 738112.7764704 ],
       [ 353161.36881741],
       [ 892585.1185592 ],
       [ 478017.49056179],
       [ 511668.73363284],
       [ 396429.46725839],
       [ 397006.605426  ],
       [ 458944.54713226],
       [ 554564.31028356],
       [ 292724.83106943],
       [ 302415.01301042],
       [ 243671.39618705],
       [ 329943.29172111],
       [ 939341.26680586],
       [ 313688.95465045],
       [ 287127.60001643],
       [ 930335.56872119],
       [ 439545.34596024],
       [ 443546.54263427],
       [ 285031.93571098],
       [ 246538.87605429],
       [ 654884.38787132],
       [ 520671.32574668],
       [ 521374.17298393],
       [ 334675.42794812],
       [ 509828.98719846],
       [ 631850.39727193],
       [ 847341.81089735],
       [ 403478.00587722],
       [ 555841.48005635],
       [ 741017.78713013],
       [ 276114.56233166],
       [ 222236.77056698],
       [ 381166.80437359],
       [ 568686.51013713],
       [1327499.97330531],
       [ 509037.76683073],
       [ 674788.94540154],
       [ 775386.06550873],
       [ 206703.63923591],
       [ 448536.86738725],
       [1051910.23678478],
       [ 235308.01349005],
       [ 404393.2677611 ],
       [ 687898.63561019],
       [ 910987.55178261],
       [ 481580.96978582],
       [ 234359.77961356],
       [ 530377.51338474],
       [ 776749.42673421],
       [ 704785.22852899],
       [ 642865.40241691],
       [ 525649.9019821 ],
       [ 486849.77575433],
       [ 191415.03787887],
       [ 427251.92561902],
       [ 625680.37881252],
       [ 496211.9214205 ],
       [ 346977.66556652],
       [ 498397.17339803],
       [ 414179.90071535],
       [ 508967.85412325],
       [ 836719.62666704],
       [ 509469.36313436],
       [ 201537.84174838],
       [ 382397.48478067],
       [ 240071.83632224],
       [ 314717.10408706],
       [ 487604.59150698],
       [ 671226.13048841],
       [ 536197.62892317],
       [1234969.45784562],
       [ 252750.07788367],
       [ 798765.39875008],
       [ 512556.68487644],
       [ 404801.41537607],
       [ 571163.91187088],
       [ 744334.48892613],
       [ 822500.75106694],
       [ 676432.33571189],
       [ 662088.63386432],
       [ 613580.16688387],
       [ 760169.82184911],
       [ 473835.80156124],
       [ 480248.99038973],
       [ 744719.99820964],
       [ 343144.9085991 ],
       [ 337624.58642831],
       [ 378782.72489125],
       [ 750504.98761044],
       [ 814723.62378024],
       [ 550644.34932464],
       [ 365210.37142839],
       [ 239815.74422322],
       [ 494509.87648394],
       [ 580284.81262384],
       [ 504583.60302384],
       [ 502576.41768184],
       [ 791328.38538384],
       [ 320044.44097898],
       [ 451012.97727227],
       [ 441246.92770963],
       [ 538235.49125439],
       [ 412473.45612899],
       [ 465688.96345936],
       [ 378812.98160844],
       [ 518719.99471676],
       [ 410870.76074187],
       [ 641091.114347  ],
       [ 564769.93189766],
       [ 420107.43072357],
       [ 612498.72000954],
       [ 258854.9417545 ],
       [ 305899.38075357],

In [40]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [41]:
mean_absolute_error(y_test,y_pred)

187383.11826628048

In [42]:
mean_squared_error(y_test,y_pred)

834459517021.8367

In [43]:
r2_score(y_test,y_pred)

0.07989841085732896